const SOURCES = [
  ['CCSD 46 Board of Education','https://d46.org/board-of-education/'],
  ['CCSD 46 District Schools','https://d46.org/schools/'],
  ['CCSD 46 Strategic Plan','https://d46.org/strategic-plan/'],
  ['Lake County Petition Packets','https://www.lakecountyil.gov/309/Petition-Packets'],
  ['IASB Information for Candidates','https://www.iasb.com/memberships-and-divisions/school-board-elections/information-for-candidates'],
  ['Illinois State Board of Elections','https://www.elections.il.gov/RunningForOffice.aspx?MID=rOlNCTNZd9A='],
  ['Illinois Report Card CCSD 46','https://irc.isbe.net/District.aspx?source=studentcharacteristics&source2=enrollment&Districtid=34049046004']
];

const actionItems = [
  {id:'ready-family-financial', section:'readiness', title:'Complete family and financial readiness assessment', priority:'Critical', window:'Before launch', owner:'Candidate + spouse/household + treasurer', how:'Block 60 minutes. List expected costs, lost work time, childcare/transportation needs, family privacy boundaries, and the maximum campaign budget the household can tolerate.', proof:'Upload/link or summarize a signed household readiness note, campaign budget draft, and named support contacts.'},
  {id:'ready-cio', section:'readiness', title:'Recruit a trusted CIO', priority:'Critical', window:'Before launch', owner:'Candidate', how:'CIO stands for Chief Information Officer. Pick someone you trust first and foremost, who is also technically curious. They do not need to be an IT professional; a reliable hobbyist, home-lab tinkerer, spreadsheet power user, small-business tech fixer, or automation-minded friend can work. Their job is to help evaluate tools, protect accounts, keep data organized, and translate tech confusion into plain English.', proof:'Record the person’s name/role, what systems they will own, backup contact, and first setup meeting date.'},
  {id:'ready-governance', section:'readiness', title:'Confirm board governance role boundaries', priority:'High', window:'Before launch', owner:'Candidate + governance reviewer', how:'Read IASB candidate guidance and district board role materials. Write down what a board member can do vs. what belongs to the superintendent/staff.', proof:'Paste a short governance do/don’t list with source links.'},
  {id:'ready-support', section:'readiness', title:'Name support system for treasurer, volunteers, comms, and advice', priority:'Critical', window:'Before launch', owner:'Candidate + campaign manager', how:'Name real people for treasurer/compliance, volunteer coordination, communications, data/tech, and personal stress support. Confirm each person understands the ask.', proof:'Record names/roles or a redacted roster plus confirmation dates.'},

  {id:'mech-eligibility', section:'mechanics', title:'Verify eligibility, forms, signature count, and filing window', priority:'Critical', window:'Immediately', owner:'Compliance lead / treasurer, reviewed by counsel if possible', how:'Call or email Lake County Clerk candidate services and check ISBE/IASB. Ask for the current school-board packet, exact office title, filing office, circulation start date, filing dates, signature minimum, signer qualifications, and required forms.', proof:'Paste the clerk/ISBE response, contact name, date, and packet link.'},
  {id:'mech-petition-plan', section:'mechanics', title:'Build petition plan with validation buffer', priority:'Critical', window:'Before circulation', owner:'Field lead + compliance lead', how:'Set a target above the legal minimum, assign trained circulators, create a signer validation spreadsheet, check registration/district boundaries, dedupe signatures, and schedule pre-filing review.', proof:'Link the petition plan, validation sheet, circulator script, and buffer target.'},
  {id:'mech-economic-interests', section:'mechanics', title:'Confirm Statement of Economic Interests process', priority:'High', window:'Before filing', owner:'Compliance lead', how:'Identify where and when the Statement of Economic Interests is filed, what receipt/proof is needed for the candidate packet, and who verifies it before filing.', proof:'Paste filing instructions, receipt plan, and responsible owner.'},
  {id:'mech-objections', section:'mechanics', title:'Ask what commonly triggers petition objections', priority:'High', window:'Before filing', owner:'Compliance lead + election lawyer if available', how:'Ask the clerk or experienced local election counsel about common school-board objection causes: wrong form, title, dates, notarization, signer eligibility, duplicates, binding/page issues, and circulator affidavit defects.', proof:'Record the risk checklist and reviewer.'},

  {id:'district-minutes', section:'district', title:'Read one year of CCSD 46 board agendas, minutes, and packets', priority:'High', window:'Exploratory', owner:'District research lead', how:'Create a month-by-month reading queue. Extract major votes, recurring public comments, budget/facilities items, and superintendent reports.', proof:'Link notes/source index with dates and URLs.'},
  {id:'district-strategic', section:'district', title:'Summarize strategic plan, facilities, finance, enrollment, communications', priority:'High', window:'Exploratory', owner:'District research lead + candidate', how:'Read official district pages and report-card data. Produce a two-page issue brief with only source-backed claims.', proof:'Link issue brief with citations.'},
  {id:'district-source-index', section:'district', title:'Build source index for all district claims used in messaging', priority:'High', window:'Exploratory', owner:'Comms lead + research lead', how:'For every public claim, capture title, URL, date accessed, quote/stat, and how it may be used safely in campaign language.', proof:'Link the source index.'},
  {id:'district-calendar', section:'district', title:'Add board/calendar observation plan for summer meetings', priority:'Medium', window:'Summer', owner:'Candidate + volunteer scheduler', how:'Identify summer board meetings and decide who attends, who takes notes, and when the team debriefs.', proof:'Link calendar entries and observation notes.'},

  {id:'terrain-stakeholders', section:'terrain', title:'Map stakeholders', priority:'High', window:'Exploratory', owner:'Field lead', how:'Create a map of parent groups, teachers/staff, admin, unions, PTA/PTO, civic leaders, municipal officials, taxpayers, and quiet-middle validators.', proof:'Link stakeholder map with contact owner and status.'},
  {id:'terrain-interviews', section:'terrain', title:'Interview 15-25 community members before announcing', priority:'High', window:'Pre-launch', owner:'Candidate + field lead', how:'Use a consistent listening script. Ask what people need from the district, what they distrust, and what they wish candidates understood.', proof:'Record anonymized interview count, themes, and dates.'},
  {id:'terrain-validate-warnings', section:'terrain', title:'Validate political-terrain warnings', priority:'High', window:'Pre-launch', owner:'Campaign manager', how:'Treat warnings as hypotheses. Confirm through public records, former candidates, board watchers, and trusted community validators.', proof:'Mark each warning as validated, rejected, or needs evidence.'},
  {id:'terrain-quiet-middle', section:'terrain', title:'Build listening plan for the quiet middle', priority:'High', window:'Exploratory', owner:'Field lead', how:'Identify people not active in online factions: school volunteers, neighbors, civic groups, and parents who avoid public fights.', proof:'Link listening plan and outreach list.'},

  {id:'ops-messaging-parent', section:'operations', module:'Messaging', title:'Parent concern matrix', priority:'High', window:'Pre-launch', owner:'Comms lead', how:'List top parent concerns, evidence, safe response, and follow-up ask.', proof:'Link completed matrix.'},
  {id:'ops-messaging-teacher', section:'operations', module:'Messaging', title:'Teacher/staff concern matrix', priority:'High', window:'Pre-launch', owner:'Comms lead + educator validator', how:'Gather themes without implying staff endorsement. Separate working conditions, student support, and governance constraints.', proof:'Link matrix with reviewer.'},
  {id:'ops-messaging-taxpayer', section:'operations', module:'Messaging', title:'Taxpayer concern matrix', priority:'High', window:'Pre-launch', owner:'Comms lead + finance reviewer', how:'Summarize taxes, budget, facilities, and accountability issues using source-backed language.', proof:'Link matrix and sources.'},
  {id:'ops-messaging-discipline', section:'operations', module:'Messaging', title:'3-message discipline', priority:'High', window:'Pre-launch', owner:'Candidate + comms lead', how:'Pick three core messages. Test whether every post, answer, and flyer supports one of them.', proof:'Paste final three messages.'},
  {id:'ops-messaging-sources', section:'operations', module:'Messaging', title:'Source-backed claims policy', priority:'Critical', window:'Launch', owner:'Comms lead', how:'No public claim goes out without a source or clearly labeled opinion. Create a pre-post review rule.', proof:'Link policy and reviewer checklist.'},
  {id:'ops-community-pta', section:'operations', module:'Community Mapping', title:'PTA/PTO map', priority:'High', window:'Exploratory', owner:'Field lead', how:'Identify organizations, meeting rhythms, public contacts, and appropriate non-disruptive listening opportunities.', proof:'Link map.'},
  {id:'ops-community-orgs', section:'operations', module:'Community Mapping', title:'Faith/community orgs', priority:'Medium', window:'Exploratory', owner:'Field lead', how:'Map community organizations and ask where school issues naturally surface.', proof:'Link outreach tracker.'},
  {id:'ops-community-business', section:'operations', module:'Community Mapping', title:'Business/civic leaders', priority:'Medium', window:'Exploratory', owner:'Candidate + field lead', how:'Identify local leaders who hear taxpayer and workforce concerns. Schedule listening conversations.', proof:'Link conversation log.'},
  {id:'ops-volunteer-roles', section:'operations', module:'Volunteer Ops', title:'Role descriptions', priority:'Critical', window:'Pre-launch', owner:'Campaign manager', how:'Write small jobs: canvasser, caller, event helper, data entry, driver, host, photographer, compliance helper.', proof:'Link role sheet.'},
  {id:'ops-volunteer-onboarding', section:'operations', module:'Volunteer Ops', title:'Onboarding script', priority:'High', window:'Pre-launch', owner:'Volunteer lead', how:'Create a 10-minute onboarding script with campaign values, legal boundaries, voter-contact expectations, and where to ask questions.', proof:'Link script.'},
  {id:'ops-volunteer-schedule', section:'operations', module:'Volunteer Ops', title:'Weekly schedule', priority:'High', window:'Pre-launch', owner:'Volunteer lead', how:'Set weekly volunteer blocks and one owner for reminders and follow-up.', proof:'Link calendar/schedule.'},
  {id:'ops-fundraising-budget', section:'operations', module:'Fundraising', title:'Budget ladder', priority:'Critical', window:'Pre-launch', owner:'Treasurer + candidate', how:'Create low/mid/high campaign budgets and what each unlocks. Include reporting/compliance assumptions.', proof:'Link budget ladder.'},
  {id:'ops-fundraising-donor', section:'operations', module:'Fundraising', title:'Donor list rules', priority:'High', window:'Pre-launch', owner:'Treasurer', how:'Define who can ask, how contributions are tracked, and when reporting rules must be checked.', proof:'Link rules and tracker.'},
  {id:'ops-digital-website', section:'operations', module:'Digital', title:'Website', priority:'Medium', window:'Launch', owner:'Digital lead', how:'Publish a simple site: bio, issues, contact, donate/volunteer if appropriate, disclaimer, and source-backed claims.', proof:'Paste URL and launch checklist.'},
  {id:'ops-digital-email', section:'operations', module:'Digital', title:'Email list', priority:'Medium', window:'Launch', owner:'Digital lead', how:'Choose a platform, create signup form, privacy language, and first welcome email.', proof:'Link form and test subscriber proof.'},
  {id:'ops-forums-brief', section:'operations', module:'Forums & Debates', title:'Issue brief book', priority:'High', window:'Before forums', owner:'Candidate + comms lead', how:'Build short answers for likely forum questions with source links and values-based framing.', proof:'Link brief book.'},
  {id:'ops-gotv-universe', section:'operations', module:'GOTV', title:'Voter-contact universe', priority:'High', window:'Final 60 days', owner:'Data/field lead', how:'Define who you are contacting, how often, by what channel, and how completion is tracked.', proof:'Link voter-contact plan or redacted counts.'},
  {id:'ops-postmortem-plan', section:'operations', module:'Postmortem', title:'Post-election postmortem plan', priority:'Medium', window:'After election', owner:'Campaign manager', how:'Schedule a postmortem before emotions fade. Capture what worked, failed, surprised, and should be public knowledge.', proof:'Link scheduled meeting or postmortem template.'},

  {id:'open-license', section:'opensource', title:'Code/docs licensing decision', priority:'High', window:'Before public launch', owner:'Project maintainer', how:'Choose license for code and documentation. Confirm third-party content can be published.', proof:'Link license files.'},
  {id:'open-stewards', section:'opensource', title:'District steward role definition', priority:'Medium', window:'Before scaling', owner:'Project maintainer', how:'Define what a district steward maintains, how updates are reviewed, and how disputes are handled.', proof:'Link role definition.'},
  {id:'open-privacy', section:'opensource', title:'Privacy/redaction review', priority:'Critical', window:'Before public launch', owner:'Privacy reviewer', how:'Remove private interview details, personal contact data, and unverified sensitive claims before publishing.', proof:'Link redaction checklist.'},
  {id:'open-corrections', section:'opensource', title:'Public correction process', priority:'High', window:'Before public launch', owner:'Project maintainer', how:'Create a way for public corrections and source updates to be submitted and reviewed.', proof:'Link correction process.'},
  {id:'open-lake-template', section:'opensource', title:'Scaling to Lake County template', priority:'Medium', window:'After CCSD 46 validation', owner:'Project maintainer', how:'Extract reusable structure without CCSD 46-specific assumptions.', proof:'Link template draft.'}
];

const tribal = [
  ['Board governance is not superintendent management','Learn policy, budget, superintendent evaluation, and public accountability boundaries before messaging.','High'],
  ['Petition errors can end campaigns early','Signature count is not enough; duplicates, nonregistered signers, wrong addresses, and form errors matter.','Critical'],
  ['Financial stress is real even in small races','Printing, childcare, transport, website, events, signs, and lost time should be planned before launch.','Critical']
];

const sectionTitles={mission:'Mission Control',readiness:'Readiness',mechanics:'Election Mechanics',district:'District Intelligence',terrain:'Political Terrain',operations:'Operations',opensource:'Open Source',tvlawyer:'TV Lawyer'};
const sectionHints={mission:'All campaign action items. Mission Control shows the next 3 incomplete actions.',readiness:'Readiness progress counts only readiness action items.',mechanics:'Election mechanics progress counts only legal/election action items.',district:'District progress counts only district research action items.',terrain:'Terrain progress counts only stakeholder/terrain action items.',operations:'Operations progress counts all operations action items across modules.',opensource:'Open-source progress counts only stewardship action items.'};
function $(id){return document.getElementById(id)}
function save(k,v){localStorage.setItem('sbcos:'+k, JSON.stringify(v))}
function load(k,d){try{return JSON.parse(localStorage.getItem('sbcos:'+k)) ?? d}catch{return d}}
let done=load('actions', {});
let proof=load('proof', {});
let showAllTasks=false, showAllSources=false, showAllTerrain=false, showAllMechanics=false, showAllDistrict=false, showAllReadiness=false, showAllOps=false, showAllOpenSource=false;
function pct(doneCount,total){return total ? Math.max(0,Math.min(100,Math.round(doneCount/total*100))) : 0}
function sectionItems(section){return section==='mission' ? actionItems : actionItems.filter(item=>item.section===section)}
function progressFor(section){const items=sectionItems(section); const complete=items.filter(item=>done[item.id]).length; return {complete,total:items.length,percent:pct(complete,items.length),items};}
function currentSection(){return document.querySelector('.section.active')?.id || 'mission'}
function renderProgress(id){
  $('sectionTitle').textContent=sectionTitles[id]||sectionTitles.mission;
  const card=document.querySelector('.progress-card');
  if(id==='tvlawyer') { card.classList.add('hidden'); return; }
  card.classList.remove('hidden');
  const p=progressFor(id);
  $('progressLabel').textContent=`${p.complete}/${p.total} action items done`;
  $('progressHint').textContent=sectionHints[id]||'';
  $('progressFill').style.width=p.percent+'%';
}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function aiFit(item){
  const specific={
    'ready-family-financial':['AI can partially help','AI can turn household concerns into a budget worksheet, stress-risk checklist, spouse/family discussion agenda, and red-flag list. Humans must make the actual financial and family commitment decision.'],
    'ready-cio':['AI can substantially help','AI can draft the CIO role description, account-security checklist, shared-drive structure, tool shortlist, and onboarding agenda. A human must choose someone trusted and give them appropriate access.'],
    'ready-governance':['AI can substantially help','AI can summarize board-governance source materials, create a can/cannot-do table, and draft scenario questions. A human should verify with official guidance and experienced board observers.'],
    'ready-support':['AI can partially help','AI can propose team roles, outreach scripts, and a staffing gap checklist. Humans must personally recruit and confirm trusted people.'],
    'mech-eligibility':['AI can partially help','AI can draft the exact email/call script for Lake County Clerk and ISBE, extract deadlines from official pages, and create a verification table. A human must confirm the official answer and keep the receipt.'],
    'mech-petition-plan':['AI can substantially help','AI can create the circulator script, signer validation spreadsheet columns, duplicate-check workflow, and buffer calculator. Humans must train circulators and verify voter eligibility with official data.'],
    'mech-economic-interests':['AI can partially help','AI can identify the likely filing steps, make a receipt checklist, and draft questions for the filing authority. A human must file the form and retain official proof.'],
    'mech-objections':['AI can substantially help','AI can build an objection-risk checklist from official guidance and known failure modes, then convert it into a pre-filing review worksheet. Counsel or an experienced election reviewer should validate the final packet.'],
    'district-minutes':['AI can substantially help','AI can summarize agendas, minutes, board packets, votes, public comments, and recurring issues into a dated research brief. Humans should review the source links and decide what matters politically.'],
    'district-strategic':['AI can substantially help','AI can synthesize the strategic plan, facilities, finance, enrollment, and communication themes into a source-backed issue brief. Humans must check nuance and local context.'],
    'district-source-index':['AI can substantially help','AI can extract source titles, URLs, dates, quotes, and claim-safe language into a source index. Humans must approve what gets used publicly.'],
    'district-calendar':['AI can substantially help','AI can scan public calendars, draft observation templates, and generate reminder text. Humans must attend or assign attendees.'],
    'terrain-stakeholders':['AI can partially help','AI can propose stakeholder categories, map public organizations, and build an outreach tracker. Humans must know who is trusted locally and handle relationship-building.'],
    'terrain-interviews':['AI can partially help','AI can draft listening scripts, consent language, note templates, and theme summaries. Humans must conduct the conversations.'],
    'terrain-validate-warnings':['AI can partially help','AI can turn each warning into evidence questions and source checks. Humans must validate sensitive political claims through trusted local judgment.'],
    'terrain-quiet-middle':['AI can partially help','AI can suggest underrepresented listening channels and outreach scripts. Humans must identify real quiet-middle validators.'],
    'ops-messaging-parent':['AI can substantially help','AI can draft the matrix, cluster parent concerns, and suggest plain-language responses. Humans must check tone and lived reality.'],
    'ops-messaging-teacher':['AI can partially help','AI can structure staff/teacher themes and safe wording that avoids implying endorsement. Humans must protect staff privacy and validate sensitivity.'],
    'ops-messaging-taxpayer':['AI can substantially help','AI can convert budget/facility data into taxpayer-facing explanations with citations. Humans must approve fiscal claims.'],
    'ops-messaging-discipline':['AI can substantially help','AI can generate and test message options against voter personas, then flag off-message language. Humans choose the final voice.'],
    'ops-messaging-sources':['AI can substantially help','AI can create the pre-publication claim review checklist and identify unsupported assertions. Humans decide whether a claim is worth making.'],
    'ops-community-pta':['AI can partially help','AI can map public PTA/PTO contacts and draft respectful listening requests. Humans must observe norms and avoid disrupting parent groups.'],
    'ops-community-orgs':['AI can partially help','AI can find public community organizations and draft outreach language. Humans must decide what is appropriate locally.'],
    'ops-community-business':['AI can partially help','AI can build a target list from public sources and draft conversation prompts. Humans must make the relationship ask.'],
    'ops-volunteer-roles':['AI can substantially help','AI can generate role descriptions, skill requirements, time commitments, and onboarding checklists. Humans must recruit and manage volunteers.'],
    'ops-volunteer-onboarding':['AI can substantially help','AI can draft the onboarding script, volunteer FAQ, legal boundaries, and first-week task list. Humans must deliver the culture and answer questions.'],
    'ops-volunteer-schedule':['AI can substantially help','AI can create weekly schedule templates and reminder messages. Humans must confirm availability and manage changes.'],
    'ops-fundraising-budget':['AI can substantially help','AI can draft low/mid/high budgets, cost assumptions, and fundraising scenarios. A treasurer or knowledgeable human must verify finance rules.'],
    'ops-fundraising-donor':['AI can partially help','AI can draft donor tracking fields, thank-you language, and compliance questions. Humans must handle relationships and reporting decisions.'],
    'ops-digital-website':['AI can substantially help','AI can draft site copy, page structure, accessibility checks, and source-backed issue pages. Humans approve publication and identity.'],
    'ops-digital-email':['AI can substantially help','AI can write signup copy, welcome emails, segmentation tags, and privacy language. Humans own the list and consent practices.'],
    'ops-forums-brief':['AI can substantially help','AI can generate likely questions, draft answer options, and identify weak claims needing sources. Humans rehearse and adapt to the room.'],
    'ops-gotv-universe':['AI can partially help','AI can design tracking fields, contact cadence, and scripts. Humans must comply with data rules and execute voter contact.'],
    'ops-postmortem-plan':['AI can substantially help','AI can create a postmortem agenda, survey, and lessons-learned template. Humans must be honest about what happened.'],
    'open-license':['AI can partially help','AI can compare common open-source license choices and draft documentation. A human should make the legal/policy choice.'],
    'open-stewards':['AI can substantially help','AI can draft steward responsibilities, review workflows, and governance templates. Humans must decide authority and accountability.'],
    'open-privacy':['AI can partially help','AI can create redaction checklists and scan for obvious private data. Humans must make final privacy judgments.'],
    'open-corrections':['AI can substantially help','AI can draft issue templates, correction workflows, and source-update rules. Humans must moderate disputes.'],
    'open-lake-template':['AI can substantially help','AI can extract reusable templates and flag CCSD-specific assumptions. Humans validate fit for each district.']
  };
  return specific[item.id] || ['AI can partially help','AI can draft checklists, templates, summaries, and review questions. Humans must verify facts, make commitments, and execute real-world work.'];
}
function actionRow(item){return `<button type="button" class="task-card title-only ${done[item.id]?'done':''}" data-open-action="${item.id}" data-card="${item.id}"><span>${esc(item.title)}</span>${done[item.id]?'<b class="done-badge">Done</b>':''}</button>`}
function bindActionControls(){
  document.querySelectorAll('[data-open-action]').forEach(el=>el.onclick=e=>openActionModal(e.currentTarget.dataset.openAction));
}
function openActionModal(id){
  const item=actionItems.find(x=>x.id===id); if(!item) return;
  const [aiLabel, aiText]=aiFit(item);
  $('modalBody').innerHTML=`<div class="modal-kicker">${esc(item.section)}${item.module?' · '+esc(item.module):''} · ${esc(item.priority)} · ${esc(item.window)}</div><h2 id="modalTitle">${esc(item.title)}</h2><div class="ai-flag"><b>${esc(aiLabel)}</b><p>${esc(aiText)}</p></div><div class="task-guidance modal-guidance"><p><b>Owner:</b> ${esc(item.owner)}</p><p><b>How:</b> ${esc(item.how)}</p><p><b>Proof needed:</b> ${esc(item.proof)}</p></div><label class="proof-label">Proof / notes that this was done<textarea id="modalProof" data-proof="${item.id}" rows="5" placeholder="Paste link, date, owner, source, decision, or notes...">${esc(proof[item.id]||'')}</textarea></label><div class="modal-actions"><button id="modalDone" class="primary-button" type="button">${done[item.id]?'Done ✓':'Mark Done'}</button><button id="modalNotDone" class="text-button" type="button">Mark not done</button></div>`;
  $('actionModal').classList.remove('hidden');
  $('modalProof').oninput=e=>{proof[id]=e.target.value;save('proof',proof)};
  $('modalDone').onclick=()=>{proof[id]=$('modalProof').value; done[id]=true; save('proof',proof); save('actions',done); closeActionModal(); render(); renderProgress(currentSection())};
  $('modalNotDone').onclick=()=>{proof[id]=$('modalProof').value; done[id]=false; save('proof',proof); save('actions',done); closeActionModal(); render(); renderProgress(currentSection())};
  setTimeout(()=>$('modalProof')?.focus(), 50);
}
function closeActionModal(){ $('actionModal').classList.add('hidden'); $('modalBody').innerHTML=''; }
function renderActionList(target, items, limit=3, expanded=false){const list=expanded?items:items.filter(item=>!done[item.id]).slice(0,limit); target.innerHTML=(list.length?list:items.slice(0,limit)).map(actionRow).join('');}
function renderAlerts(){
  const alerts=[];
  if(!done['ready-family-financial']) alerts.push(`<button class="warning compact alert-link" data-section="readiness" data-focus="ready-family-financial"><b>Financial readiness needs work.</b> Complete the family/financial readiness action.</button>`);
  $('warnings').innerHTML=alerts.join('') || '<div class="ok compact"><b>No blocking readiness flags in this first pass.</b> Keep verifying legal mechanics and human support.</div>';
}
function render(){
 renderAlerts();
 const all=progressFor('mission');
 renderActionList($('taskList'), all.items, 3, showAllTasks); $('toggleAllTasks').textContent=showAllTasks?'Show fewer':`Show all ${all.total}`;
 renderReadiness(); renderMechanics(); renderDistrict(); renderTerrain(); renderOps(); renderOpenSource(); bindActionControls();
}
function renderReadiness(){const items=sectionItems('readiness'); renderActionList($('readinessList'), items, 3, showAllReadiness); $('toggleReadiness').textContent=showAllReadiness?'Show fewer':`Show all ${items.length}`;}
function renderMechanics(){const items=sectionItems('mechanics'); renderActionList($('mechanicsList'), items, 3, showAllMechanics); $('toggleMechanics').textContent=showAllMechanics?'Show fewer':`Show all ${items.length}`;}
function renderDistrict(){const cards=[['Board cadence','Meets generally twice monthly; one summer meeting per month.'],['Schools','Eight-school/facility structure across K-8 and early childhood.'],['Strategic signals','Finance transparency, facilities, technology, and communications.']]; const items=sectionItems('district'); $('districtCards').innerHTML=cards.map(c=>`<div class="mini-card"><b>${c[0]}</b><span>${c[1]}</span></div>`).join('')+`<div class="panel-card compact-card district-actions"><div class="card-head"><h3>District action items</h3><button id="toggleDistrict" class="text-button">${showAllDistrict?'Show fewer':`Show all ${items.length}`}</button></div>${(showAllDistrict?items:items.slice(0,3)).map(actionRow).join('')}</div>`; const btn=$('toggleDistrict'); if(btn) btn.onclick=()=>{showAllDistrict=!showAllDistrict;renderDistrict();bindActionControls()}; $('sources').innerHTML=(showAllSources?SOURCES:SOURCES.slice(0,4)).map(s=>`<li><a href="${s[1]}" target="_blank" rel="noreferrer">${s[0]}</a></li>`).join(''); $('toggleSources').textContent=showAllSources?'Show fewer':'Show all sources';}
function renderTerrain(){const items=sectionItems('terrain'); $('tribalCards').innerHTML=(showAllTerrain?items:items.slice(0,3)).map(actionRow).join('')+tribal.map(t=>`<div class="knowledge"><span class="pill ${t[2]==='Critical'?'red':'gold'}">${t[2]}</span><b>${t[0]}</b><p>${t[1]}</p></div>`).join(''); $('toggleTerrain').textContent=showAllTerrain?'Show fewer':`Show all ${items.length}`;}
function renderOps(){const sel=$('opsSelect'); const keys=[...new Set(sectionItems('operations').map(item=>item.module))]; if(!sel.dataset.ready){sel.innerHTML=keys.map(k=>`<option value="${k}">${k}</option>`).join(''); sel.dataset.ready='1'; sel.onchange=()=>{showAllOps=false;renderOps();bindActionControls();renderProgress('operations')}} const k=sel.value||keys[0]; const moduleItems=sectionItems('operations').filter(item=>item.module===k); $('opsDetail').innerHTML=(showAllOps?moduleItems:moduleItems.slice(0,3)).map(actionRow).join(''); $('toggleOps').textContent=showAllOps?'Show fewer':`Show all ${moduleItems.length}`; $('opsPreview').innerHTML=keys.slice(0,3).map(k=>{const items=sectionItems('operations').filter(item=>item.module===k); const c=items.filter(item=>done[item.id]).length; return `<button class="mini-card" data-ops-select="${k}"><b>${k}</b><span>${c}/${items.length} done</span></button>`}).join(''); document.querySelectorAll('[data-ops-select]').forEach(b=>b.onclick=()=>{sel.value=b.dataset.opsSelect;showAllOps=false;renderOps();bindActionControls();renderProgress('operations')});}
function renderOpenSource(){const items=sectionItems('opensource'); $('openSourceSteps').innerHTML=(showAllOpenSource?items:items.slice(0,3)).map(actionRow).join(''); $('toggleOpenSource').textContent=showAllOpenSource?'Show fewer':`Show all ${items.length}`;}
function focusAction(id){setTimeout(()=>{const el=document.querySelector(`[data-card="${id}"]`); if(el){el.scrollIntoView({behavior:'smooth',block:'center'}); el.classList.add('focused'); setTimeout(()=>el.classList.remove('focused'),1800)}},50)}
function show(id, focusId){document.querySelectorAll('.section').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.section===id));render();renderProgress(id);if(focusId) focusAction(focusId); else window.scrollTo(0,0)}
function tvLawyerContext(){return {product:'School Board Campaign Operating System',referenceDistrict:'Community Consolidated School District 46 (CCSD 46), Illinois',assumedJurisdiction:'Lake County, Illinois / Illinois school board consolidated election context; verify with official authorities',sources:SOURCES.map(([title,url])=>({title,url})),actionProgress:progressFor('mission'),criticalLegalTasks:sectionItems('mechanics').map(t=>({title:t.title,priority:t.priority,window:t.window,done:!!done[t.id],proof:proof[t.id]||''})),highRiskTribalKnowledge:tribal.filter(t=>t[2]==='Critical').map(t=>({title:t[0],lesson:t[1],severity:t[2]}))};}
function linkify(s){return esc(s).replace(/(https?:\/\/[^\s<]+)/g,'<a href="$1" target="_blank" rel="noreferrer">$1</a>')}
function setTvLawyerMessage(div,role,text){div.innerHTML='<b>'+(role==='user'?'You':'TV Lawyer')+':</b> '+linkify(text).replace(/\n/g,'<br>')}
function appendTvLawyerMessage(role,text){const log=$('tvLawyerLog'); if(!log) return null; const div=document.createElement('div'); div.className='chat-msg '+(role==='user'?'user':'bot'); setTvLawyerMessage(div,role,text); log.appendChild(div); log.scrollTop=log.scrollHeight; return div;}
function tvLawyerFallbackPrompt(message){
  const ctx=tvLawyerContext();
  return `You are TV Lawyer, a legal due-diligence assistant for a first-time school board campaign. Start with: "I'm not a lawyer, but I play one on TV." Make clear this is not legal advice, not a lawyer, not a replacement for qualified counsel, and not something to rely on for legal decisions. Be concise and to the point. Answer as pre-counsel due diligence. Assumed context: ${ctx.referenceDistrict}; ${ctx.assumedJurisdiction}. Use these source leads where relevant: ${ctx.sources.map(s=>s.title+': '+s.url).join('; ')}. Critical legal tasks: ${ctx.criticalLegalTasks.map(t=>`${t.title} (${t.done?'done':'not done'})`).join('; ')}. User question: ${message}. Structure the answer as: short answer; assumptions/jurisdiction; what to verify with official authorities or counsel; practical next steps; questions to ask the clerk/counsel.`;
}
function tvLawyerFallbackHtml(message){
  const prompt=tvLawyerFallbackPrompt(message);
  const url='https://chat.openai.com/?q='+encodeURIComponent(prompt);
  return `I can’t reach the local TV Lawyer server from this page. That is expected on a static GitHub Pages demo.\n\nUse this prompt in ChatGPT or another AI chat tool to get a useful legal due-diligence answer:\n\n${prompt}\n\nOpen ChatGPT with this prompt: ${url}`;
}
async function askTvLawyer(){const q=$('tvLawyerQuestion'), btn=$('tvLawyerAsk'), status=$('tvLawyerStatus'); const message=q.value.trim(); if(!message){status.textContent='Ask a question first.';return;} appendTvLawyerMessage('user',message); const pending=appendTvLawyerMessage('bot','Thinking… checking the campaign context and preparing a legal due-diligence answer.'); q.value=''; btn.disabled=true; status.textContent='TV Lawyer is thinking…'; try{const res=await fetch('/api/hermes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'tv-lawyer',message,dashboardContext:tvLawyerContext(),shouldReload:false})}); if(!res.ok) throw new Error('TV Lawyer server unavailable'); const data=await res.json().catch(()=>({error:'Invalid JSON response'})); const answer=(data.error?data.error+'\n\n':'')+(data.reply||'No answer returned.'); setTvLawyerMessage(pending,'bot',answer); status.textContent='Answered. No dashboard reload triggered.';}catch(err){setTvLawyerMessage(pending,'bot',tvLawyerFallbackHtml(message)); status.textContent='Server unavailable — fallback prompt generated.';} finally{btn.disabled=false;}}
function setup(){document.addEventListener('click',e=>{const target=e.target.closest('[data-section]'); if(target){show(target.dataset.section,target.dataset.focus)}}); $('toggleAllTasks').onclick=()=>{showAllTasks=!showAllTasks;render();renderProgress(currentSection())}; $('toggleReadiness').onclick=()=>{showAllReadiness=!showAllReadiness;renderReadiness();bindActionControls()}; $('toggleSources').onclick=()=>{showAllSources=!showAllSources;renderDistrict();bindActionControls()}; $('toggleTerrain').onclick=()=>{showAllTerrain=!showAllTerrain;renderTerrain();bindActionControls()}; $('toggleMechanics').onclick=()=>{showAllMechanics=!showAllMechanics;renderMechanics();bindActionControls()}; $('toggleOps').onclick=()=>{showAllOps=!showAllOps;renderOps();bindActionControls()}; $('toggleOpenSource').onclick=()=>{showAllOpenSource=!showAllOpenSource;renderOpenSource();bindActionControls()}; $('tvLawyerAsk').addEventListener('click',askTvLawyer); $('tvLawyerQuestion').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')askTvLawyer()}); $('modalClose').onclick=closeActionModal; $('actionModal').addEventListener('click',e=>{if(e.target.id==='actionModal') closeActionModal()}); document.addEventListener('keydown',e=>{if(e.key==='Escape') closeActionModal()}); window.__sbcos={actionItems,progressFor,sectionItems,done,proof,openActionModal}; render(); show('mission');}
document.addEventListener('DOMContentLoaded',setup);
